name: Script Test
on: push

jobs:
  unit-test:
    name: Run script/test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test
        run: node script/test/check.js  
