name: Run Ruby
on: push

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v1
      - name: Set Ruby  
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run Ruby
        run: ruby ruby/index.rb
