name: Run Ruby
on: 
  push:
    paths:
    - 'ruby/**'

jobs:
  hello:
    name: hello
    strategy:
      matrix:
        ruby: [2.5, 2.7, '3.0']
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v1
      - name: Set Ruby  
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Ruby
        run: ruby ruby/index.rb
